name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_timezone: Europe/Paris
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_limit: 0
          plugin_languages_recent_load: 800
          plugin_languages_recent_days: 30
          plugin_languages_aliases: RenderScript:Rust
          plugin_languages_ignored: Hack,Roff,TeX,C
          # plugin_stargazers: yes
          plugin_achievements: yes
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_filter: stars:>100 
          plugin_notable_self: yes
